### ISSUE TITLE
Page: About the plan

### ISSUE THREAD

**Issue by madsnedergaard** [Jacse/worlds-best-climate-plan#53]
## Todo

- [ ] Update global styling
- [ ] Make it nicer (stretch-goal)

**Comment by martincollignon** [comment]
Strech goal:
- certain words are highlighted (equivalent of footnotes)
- these highlights are related to the information boxes on the side
- an information box can have multiple sources (only one should be visible, it could be a carousel-like information box.
- as there are multiple highlights, clicking on a specific highlight would bring the relevant source in the information box
- likewise, navigating to a certain source should highlight the relevant text.

Inspiration for UX: https://stripe.com/en-dk/jobs

**Comment by martincollignon** [comment]
Copy to be implemented: https://docs.google.com/document/d/1ctl8C8fdI7GHxYnj0frSxt72isy-5lj1btt31o0jjx4/edit

**Comment by Jacse** [comment]
I don't really feel like the Stripe design fits in with the overall design of the page and I think we should have a discussion around how it could otherwise look. Here's the current (Stripe-like) design:

![Screen Shot 2020-03-02 at 09 08 21-fullpage](https://user-images.githubusercontent.com/3637499/75657212-f8922100-5c65-11ea-9695-a82e737438ce.png)

A quick alternative look (needs more drawings, but the site was down at time of writing):

![Screen Shot 2020-03-02 at 09 06 01-fullpage](https://user-images.githubusercontent.com/3637499/75657134-d4364480-5c65-11ea-9cc5-a78e702c7913.png)

**Comment by sjwinther** [comment]
I think your bottom design looks good! I'm split between having them appear on hover or showing them in the margins. Neither are super elegant solutions on mobile, but at least on mobile we can have them appear on click instead.

![image](https://user-images.githubusercontent.com/7511088/75790663-cff44f00-5d6b-11ea-95db-dbd25b979985.png)

Mocked this up in the original design, but I honestly prefer your solution as it gives more context. Maybe lets do that, and truncate long pusblishers, so it doesn't wrap (last link, bottom right in your screenshot)?

**Comment by wandererfrog** [comment]
BTW guys, don't forget my commit was made following an UPwork ad. 
My code ended up merged into master and it was done according to the specs.

How are you thinking of handling this?

**Comment by martincollignon** [comment]
I discussed with @wandererfrog :)

**Comment by martincollignon** [comment]
FYI @Jacse someone on upwork helped me do this for the sources / links. https://docs.google.com/spreadsheets/d/1HfrE2drgWT0253JinBBShP7g135ChNlA1G3GIYd73D0/edit#gid=0

**Comment by Jacse** [comment]
Closed by #74
